services:

  mysql:
    image: mysql:8.4
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointment_booking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis7
    restart: always
    ports:
      - "6379:6379"

  app:
    image: booking-appointment
    container_name: booking-app
    restart: always
    depends_on:
      - mysql
      - redis
    env_file:
      - ./app/.env.docker
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

volumes:
  mysql_data: