spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: 
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
        database-platform: org.hibernate.dialect.MySQLDialect
    devtools:
        restart:
            enabled: true
server:
    port: 8080
    servlet:
        context-path: /api